version : "3"
services :
  db:
    image : postgres:11.3-alpine
    environment:
      - POSTGRES_DB=gcc_welfare
      - POSTGRES_PASSWORD=gcc_welfare
    ports :
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image : nginx:1.17.0-alpine
    deploy:
      mode: global
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - data:/var/tmp
      - static:/etc/static
    depends_on:
      - app
    ports: 
      - 80:80
      
  app :
    image: gcc-welfare
    volumes :
      - .:/usr/src/app  #remove in production
      - data:/var/tmp
      - static:/etc/static
    environment :
      - DEPLOY_ENV=dev
      - STATIC_ROOT=/etc/static
      - MEDIA_ROOT=/etc/static/media
      - NODE_PATH=/tmp/node_modules
      - DATABASE_URL=postgres://postgres:gcc_welfare@db:5432/gcc_welfare
      - AFRICASTALKING_USERNAME=sandbox
      - AFRICASTALKING_API_KEY=c0e35b894c6624c56aae09f185500e447e5106d99e90c9cc531a28f69a0d9f50

    depends_on:
      - db

volumes:
  data:
  static:
  pgdata:
