version : "3"
services :
  db:
    image : postgres:11.3-alpine
    environment:
      - POSTGRES_DB=gcc_welfare
      - POSTGRES_PASSWORD=gcc_welfare
    ports :
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image : nginx:1.17.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/etc/static
    depends_on:
      - backend
    ports: 
      - 80:80
      
  backend:
    build: backend/
    volumes :
      - ./backend:/usr/src/app  #remove in production
      - static:/etc/static
    environment :
      - DEPLOY_ENV=stagging
      - STATIC_ROOT=/etc/static
      - MEDIA_ROOT=/etc/static/media
      - NODE_PATH=/tmp/node_modules
      - DATABASE_URL=postgres://postgres:gcc_welfare@db:5432/gcc_welfare
      - AFRICASTALKING_USERNAME=sandbox
      - AFRICASTALKING_API_KEY=c0e35b894c6624c56aae09f185500e447e5106d99e90c9cc531a28f69a0d9f50
    depends_on:
      - db

  frontend:
    build: frontend/


  redis:
    image: redis:5.0.7-alpine
    volumes:
      - redis-data:/var/lib/redis

volumes:
  static:
  pgdata:
  redis-data:
