version : "3"
services :
  db:
    image : postgres:11.3-alpine
    environment:
      - POSTGRES_DB=gcc_welfare
      - POSTGRES_PASSWORD=gcc_welfare
    ports :
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image : nginx:1.17.0-alpine
    deploy:
      mode: global
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - data:/var/tmp
      - static:/etc/static
    depends_on:
      - app
    ports: 
      - 80:80
      
  app :
    image: gcc-welfare
    volumes :
      - .:/usr/src/app  #remove in production
      - data:/var/tmp
      - static:/etc/static
    environment :
      - DEPLOY_ENV=prod
      - NODE_PATH=/tmp/node_modules
      - DATABASE_URL=postgres://postgres:gcc_welfare@db:5432/gcc_welfare
      - AFRICASTALKING_USERNAME=gitigi
      - AFRICASTALKING_API_KEY=6c4c9f391ba14da5f5805e449a7b009ee343b799b4a43abef84285e52247030f

    depends_on:
      - db

volumes:
  data:
  static:
  pgdata:
