version : "3"
services :
  db:
    image : postgres:11.3-alpine
    environment:
      - POSTGRES_DB=gcc_welfare
      - POSTGRES_PASSWORD=gcc_welfare
    ports :
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image : nginx:1.17.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/etc/static
    depends_on:
      - backend
    ports: 
      - 8300:80
      
  backend:
    build: backend/
    volumes :
      - ./backend:/usr/src/app  #remove in production
      - static:/etc/static
    environment :
      - DEPLOY_ENV=prod
      - STATIC_ROOT=/etc/static
      - MEDIA_ROOT=/etc/static/media
      - NODE_PATH=/tmp/node_modules
      - DATABASE_URL=postgres://postgres:gcc_welfare@db:5432/gcc_welfare
      - AFRICASTALKING_USERNAME=gitigi
      - AFRICASTALKING_API_KEY=6c4c9f391ba14da5f5805e449a7b009ee343b799b4a43abef84285e52247030f
      - BIZSMS_USER_ID=1219
      - BIZSMS_PASSWORD=gcc2019password
      - BIZSMS_SENDER_ID=GCC_KAYOLE
    depends_on:
      - db

  frontend:
    build: frontend/

  redis:
    image: redis:5.0.7-alpine
    volumes:
      - redis-data:/var/lib/redis

volumes:
  static:
  pgdata:
  redis-data:
