# Generated by Django 2.2.1 on 2019-06-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='parent_name_father',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='parent_name_mother',
            new_name='mother_name',
        ),
    ]
