# Generated by Django 2.2.1 on 2019-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190602_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_no',
            field=models.IntegerField(unique=True),
        ),
    ]
