# Generated by Django 2.2.1 on 2019-06-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190602_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('method', models.CharField(choices=[('CA', 'cash'), ('BA', 'bank'), ('MP', 'mpesa')], default='CA', max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
            ],
        ),
    ]
