# Generated by Django 2.2.1 on 2019-06-15 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_member_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
