# Generated by Django 2.2.1 on 2019-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('target', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, default='', max_length=10)),
                ('contribution', models.CharField(blank=True, default='', max_length=10)),
                ('contacts', models.TextField(blank=True, default='')),
            ],
        ),
    ]
