# Generated by Django 2.2.1 on 2019-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='date',
            field=models.DateField(),
        ),
    ]
