# Generated by Django 2.2.1 on 2019-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='disbursement',
            field=models.CharField(choices=[('CA', 'Cash'), ('CQ', 'Cheque')], default='CA', max_length=2),
        ),
    ]
