# Generated by Django 2.2.1 on 2019-06-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190627_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothered', to='core.Member'),
        ),
    ]
