# Generated by Django 2.2.1 on 2019-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_member_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
