# Generated by Django 2.2.1 on 2019-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20190712_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_no',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
