# Generated by Django 2.2.1 on 2019-08-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='start_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
