# Generated by Django 2.2.1 on 2019-09-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_payment_start_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
            ],
        ),
    ]
