# Generated by Django 2.2.1 on 2019-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('middle_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('id_no', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.CharField(default='', max_length=30)),
                ('nhif_no', models.CharField(default='', max_length=30)),
                ('spouse_name', models.CharField(default='', max_length=40)),
                ('spouse_id_no', models.IntegerField()),
                ('spouse_mobile_no', models.CharField(max_length=15)),
                ('children', models.TextField()),
                ('parent_name_father', models.CharField(default='', max_length=40)),
                ('parent_name_mother', models.CharField(default='', max_length=40)),
                ('suspended', models.BooleanField(default=False)),
            ],
        ),
    ]
