# Generated by Django 2.2.1 on 2019-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CA', 'cash'), ('BK', 'bank'), ('MP', 'mpesa')], default='CA', max_length=2),
        ),
    ]
