# Generated by Django 2.2.1 on 2019-06-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190615_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='father_name',
            new_name='father_first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='member',
            name='father_last_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='father_middle_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_first_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_last_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_middle_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_first_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_last_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_middle_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
