# Generated by Django 2.2.1 on 2019-06-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190624_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('disbursement', models.CharField(choices=[('CA', 'cash'), ('BK', 'bank'), ('MP', 'mpesa')], default='CA', max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
            ],
        ),
    ]
