# Generated by Django 2.2.1 on 2019-06-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Member'),
        ),
    ]
