# Generated by Django 2.2.1 on 2019-06-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190627_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='mother',
        ),
        migrations.AlterField(
            model_name='child',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Member'),
        ),
    ]
