# Generated by Django 2.2.1 on 2019-07-12 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190712_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
    ]
