# Generated by Django 2.2.1 on 2019-07-16 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20190716_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
