# Generated by Django 2.2.1 on 2019-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_bankingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingnotification',
            name='name',
            field=models.CharField(default='paul', max_length=50),
            preserve_default=False,
        ),
    ]
