# Generated by Django 2.2.1 on 2020-06-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_bankingnotification_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, default='')),
                ('mobile_no', models.CharField(blank=True, default='', max_length=30)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Notification')),
            ],
        ),
    ]
