# Generated by Django 2.2.1 on 2020-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='status_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='status_desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
